#! /usr/bin/python
# -*- coding: utf-8 -*-

__author__ = 'Raúl Jornet Calomarde'
__contact__ = 'rjornetc@openmailbox.org'
__copyright__ = 'Copyright © 2015, Raúl Jornet Calomarde'
__license__ = '''License GPLv3+: GNU GPL version 3 or any later
This program isfree software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or any later version. This program
is distributed  in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details.
<http://www.gnu.org/licenses/>'''
__date__ = '2015-03-14'
__version__ = '0.1'


import sys, getopt
from random import choice

CIFRAS=[100,50,25,10,1,2,3,4,5,6,7,8,9]
VOWELS=         ['A'    ,'E'    ,'I'    ,'O'    ,'U']
VOWELS_PROB=    [3,     ,2      ,2      ,2      ,2]

#http://rosettacode.org/wiki/Probabilistic_choice#Python
def probchoice(items, probs):
  '''\
  Splits the interval 0.0-1.0 in proportion to probs
  then finds where each random.random() choice lies
  '''
 
  prob_accumulator = 0
  accumulator = []
  for p in probs:
    prob_accumulator += p
    accumulator.append(prob_accumulator)
 
  while True:
    r = random.random()
    yield items[bisect.bisect(accumulator, r)]

if __name__ == '__main__':

    try:
        opts, args = getopt.getopt(sys.argv[1:],'hv',['help','version'])
    except getopt.GetoptError:
        print('TODO')#TODO: Help string
        sys.exit(2)
    for opt, arg in opts:
        if opt in ('-h', '--help'):
        print('TODO')#TODO: Help string
            sys.exit()
        elif opt in ('-v', '--version'):
            print ('TODO ' + __version__ + '\n' + __copyright__ + '\n' + __license__)#TODO: App name
            sys.exit()